<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RootNamespace>FloatingDock</RootNamespace>
    <AssemblyName>FloatingDock</AssemblyName>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Version>1.0.0</Version>
    <Authors>roseion</Authors>
    <Product>FloatingDock</Product>
    <Description>Windows 浮动 Dock 托盘：置顶、拖放快捷方式、多托盘、材质主题</Description>
  </PropertyGroup>



</Project>
